# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7db7673abc2be52f77f567e41cd981ba7b1fd15981af358bd27283b0686c020e02d5a6debc4281846c15e4ac861831638228d6d431dfc0fdde3306061acb893f

test:
  secret_key_base: 5f9bcfedde95c38317b02b7e864a99a3852539f16e90acb259ebc91b5d1ba21853768df1e947310c269a775d2d1b24c5c51deefcf3986e8228fbcdf96e0d9ef6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
